import type { SourceDefinition, SourceId, SourceSnapshot } from './types';

export const SOURCE_IDS: SourceId[] = [
  'ticktick',
  'radall',
  'gmail',
  'outlook',
  'resale',
  'role',
  'candle',
  'income',
  'move',
  'repair',
  'self',
];

export const sources: SourceDefinition[] = [
  {
    id: 'ticktick',
    number: '01',
    name: 'TickTick',
    shortName: 'TickTick',
    label: 'Routines · habits · tasks',
    description: 'Daily routines, habits, and open tasks. API adapter stub — wire TickTick later.',
    action: 'Open TickTick',
    marker: '✓',
    eyebrow: 'Routines and habits',
    intro: 'Habits, routines, and tasks will land here once the TickTick adapter is connected.',
    feature: 'Starred TickTick items',
    empty: 'Connect TickTick to feature habits and tasks here.',
    url: 'https://ticktick.com',
    bridge: 'none',
    metrics: [
      { key: 'open', label: 'Open tasks' },
      { key: 'habits', label: 'Habits today' },
      { key: 'overdue', label: 'Overdue' },
    ],
  },
  {
    id: 'radall',
    number: '02',
    name: 'Radall Finances',
    shortName: 'Radall',
    label: 'Task list · finances',
    description: 'Finance Task list from the Radall Google Sheet. Sheets adapter stub for now.',
    action: 'Open Radall sheet',
    marker: '$',
    eyebrow: 'Finances task list',
    intro: 'Open finance tasks from the Radall sheet. Live rows arrive once the Sheets adapter is wired.',
    feature: 'Starred finance tasks',
    empty: 'Connect the Radall sheet adapter to feature finance tasks here.',
    url: 'https://docs.google.com/spreadsheets/d/19rw8MAYTZ70Qy2GFAi0DaCGdsp7hQc67l8nkvw17jQk/edit',
    bridge: 'none',
    metrics: [
      { key: 'open', label: 'Open tasks' },
      { key: 'dueSoon', label: 'Due soon' },
      { key: 'done', label: 'Done' },
    ],
  },
  {
    id: 'gmail',
    number: '03',
    name: 'Gmail Starred',
    shortName: 'Gmail',
    label: 'Action emails',
    description: 'Starred Gmail threads that need action. Gmail API adapter stub for now.',
    action: 'Open Gmail',
    marker: '✉',
    eyebrow: 'Starred action mail',
    intro: 'Starred emails that need a reply or decision. Connect Gmail API to populate this card.',
    feature: 'Starred action emails',
    empty: 'Connect Gmail to show starred action emails here.',
    url: 'https://mail.google.com/mail/u/0/#starred',
    bridge: 'none',
    metrics: [
      { key: 'starred', label: 'Starred' },
      { key: 'unread', label: 'Unread starred' },
      { key: 'action', label: 'Needs action' },
    ],
  },
  {
    id: 'outlook',
    number: '04',
    name: 'Outlook',
    shortName: 'Outlook',
    label: 'Job inquiries',
    description: 'Job inquiry threads from Outlook. Stub until Microsoft Graph is connected.',
    action: 'Open Outlook',
    marker: '▣',
    eyebrow: 'Job inquiries',
    intro: 'Job inquiry mail from Outlook will appear here after the Graph adapter is wired.',
    feature: 'Starred inquiries',
    empty: 'Connect Outlook to feature job inquiries here.',
    url: 'https://outlook.live.com/mail/',
    bridge: 'none',
    metrics: [
      { key: 'inquiries', label: 'Inquiries' },
      { key: 'unread', label: 'Unread' },
      { key: 'followUp', label: 'Follow-ups' },
    ],
  },
  {
    id: 'resale',
    number: '05',
    name: 'Resale Hub',
    shortName: 'Resale',
    label: 'Listings and sales',
    description: 'Items listed, sold, views, and starred resale actions via postMessage bridge.',
    action: 'Open resale hub',
    marker: '◇',
    eyebrow: 'Listings and sales',
    intro: 'Live resale numbers and the actions you starred in the Resale Hub.',
    feature: 'Starred resale actions',
    empty: 'Star an action in the Resale Hub to show it here.',
    url: 'https://randymcfarland1227-wq.github.io/sell-hub/',
    bridge: 'iframe',
    allowedOrigins: ['https://randymcfarland1227-wq.github.io'],
    metrics: [
      { key: 'listed', label: 'Items listed' },
      { key: 'sold', label: 'Items sold' },
      { key: 'activeListings', label: 'Active listings' },
      { key: 'listingViews', label: 'Listing views' },
    ],
  },
  {
    id: 'role',
    number: '06',
    name: 'Role Hub',
    shortName: 'Role',
    label: 'Applications and pipeline',
    description: 'Job applications, pipeline, and starred roles from the Role Hub (Apps Script).',
    action: 'Open Role Hub',
    marker: '↗',
    eyebrow: 'Applications and pipeline',
    intro: 'Live application numbers and the pipeline items you starred in the Role Hub.',
    feature: 'Starred pipeline items',
    empty: 'Star a pipeline item in the Role Hub to show it here.',
    url: 'https://script.google.com/macros/s/AKfycbyYuq1_GDfbLtx1YZwIk7Khvewegl3_xocLnM_gv7zzujapMXxxXDlgWsqaiCiI4a9EIA/exec',
    bridge: 'iframe',
    allowedOrigins: ['.googleusercontent.com', 'https://script.google.com'],
    metrics: [
      { key: 'applied', label: 'Jobs applied' },
      { key: 'pipeline', label: 'Jobs in pipeline' },
      { key: 'ready', label: 'Ready to apply' },
      { key: 'activeRecords', label: 'Active job records' },
    ],
  },
  {
    id: 'candle',
    number: '07',
    name: 'Peculiar Candle',
    shortName: 'Candle',
    label: 'Pre-launch placeholder',
    description: 'Placeholder card only. Candle pre-launch wiring comes in a later pass.',
    action: 'Coming soon',
    marker: '◒',
    eyebrow: 'Pre-launch',
    intro: 'Peculiar Candle Pre Launch is a placeholder. Metrics and bridge arrive later.',
    feature: 'Starred candle items',
    empty: 'Candle source is a placeholder for now.',
    url: null,
    bridge: 'none',
    placeholder: true,
    metrics: [
      { key: 'jarsAvailable', label: 'Jars available' },
      { key: 'jarsInUse', label: 'Jars in use' },
      { key: 'totalPoured', label: 'Total poured' },
    ],
  },
  {
    id: 'income',
    number: '08',
    name: 'Income & Venture Lab',
    shortName: 'Venture',
    label: 'Income experiments',
    description: 'Income and venture experiments. Bridge stub until the lab posts snapshots.',
    action: 'Open Venture Lab',
    marker: '◈',
    eyebrow: 'Income experiments',
    intro: 'Venture experiments and income tracks. Connect postMessage from the lab site later.',
    feature: 'Starred ventures',
    empty: 'Star a venture in Income & Venture Lab to show it here.',
    url: 'https://randymcfarland1227-wq.github.io/income-venture-lab/',
    bridge: 'iframe',
    allowedOrigins: ['https://randymcfarland1227-wq.github.io'],
    metrics: [
      { key: 'active', label: 'Active ventures' },
      { key: 'ideas', label: 'Ideas' },
      { key: 'revenue', label: 'Revenue tracks' },
    ],
  },
  {
    id: 'move',
    number: '09',
    name: 'Move OS',
    shortName: 'Move',
    label: 'Movement and training',
    description: 'Movement OS board. Bridge stub until Move OS posts snapshots.',
    action: 'Open Move OS',
    marker: '◎',
    eyebrow: 'Movement OS',
    intro: 'Training and movement status from Move OS once the bridge is live.',
    feature: 'Starred move items',
    empty: 'Star an item in Move OS to show it here.',
    url: 'https://randymcfarland1227-wq.github.io/move-os/',
    bridge: 'iframe',
    allowedOrigins: ['https://randymcfarland1227-wq.github.io'],
    metrics: [
      { key: 'sessions', label: 'Sessions' },
      { key: 'streak', label: 'Streak' },
      { key: 'planned', label: 'Planned' },
    ],
  },
  {
    id: 'repair',
    number: '10',
    name: 'Site Repair Log',
    shortName: 'Repair',
    label: 'Site repair board',
    description: 'Repair log board for sites. Bridge stub until the hub posts snapshots.',
    action: 'Open Repair Log',
    marker: '⚒',
    eyebrow: 'Site repair board',
    intro: 'Open and starred repair cards from the Site Repair Log Hub.',
    feature: 'Starred repair cards',
    empty: 'Star a repair card in the Site Repair Log to show it here.',
    url: 'https://randymcfarland1227-wq.github.io/site-repair-log/#/board',
    bridge: 'iframe',
    allowedOrigins: ['https://randymcfarland1227-wq.github.io'],
    metrics: [
      { key: 'open', label: 'Open repairs' },
      { key: 'inProgress', label: 'In progress' },
      { key: 'done', label: 'Done' },
    ],
  },
  {
    id: 'self',
    number: '11',
    name: 'Self',
    shortName: 'Self',
    label: 'Hub-native inbox',
    description: 'Capture inbox stored in this browser. Star items to feature them; complete locally now.',
    action: 'Open Self inbox',
    marker: '✦',
    eyebrow: 'Capture inbox',
    intro: 'Quick capture that lives on the hub. Star to feature; complete here. Categorize-to-origin comes later.',
    feature: 'Starred Self items',
    empty: 'Add and star a Self note to feature it here.',
    url: null,
    bridge: 'local',
    metrics: [
      { key: 'open', label: 'Open' },
      { key: 'starred', label: 'Starred' },
      { key: 'done', label: 'Done' },
    ],
  },
];

export const sourceById = Object.fromEntries(sources.map(s => [s.id, s])) as Record<SourceId, SourceDefinition>;

export function emptySnapshot(id: SourceId): SourceSnapshot {
  return { source: id, metrics: {}, featured: [], tasks: [], refreshedAt: '' };
}

export function emptySnapshots(): Record<SourceId, SourceSnapshot> {
  return Object.fromEntries(SOURCE_IDS.map(id => [id, emptySnapshot(id)])) as Record<SourceId, SourceSnapshot>;
}

/** Map legacy Work Room source ids onto Life Hub ids */
export function normalizeSourceId(raw: string): SourceId | null {
  if (raw === 'search') return 'role';
  if ((SOURCE_IDS as string[]).includes(raw)) return raw as SourceId;
  return null;
}
